spring:

    datasource:
        url: jdbc:h2:file:./src/main/resources/db/database;DB_CLOSE_DELAY=-1
        driverClassName: org.h2.Driver
        username: sa
        password:

    h2:
        console:
            enabled: true
            path: /h2-console

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
            dialect: org.hibernate.dialect.H2Dialect
